spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zheliujing007/configurationTest
          searchPaths: respo/config-repo
#          username:
#          password:

server:
  port: 9524
